### ISSUE TITLE
CollectionAdmin.state broken in 5.5

### ISSUE THREAD

**Issue by relwell** [solrcloudpy/solrcloudpy#28]
```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/solrcloudpy-1.8.0-py2.7.egg/solrcloudpy/collection/admin.py", line 235, in state
    return data[self.name]
KeyError
```

**Comment by relwell** [comment]
Looks like the schema has changed here and we just missed upgrading it. This should include a test to make sure it works across all deployments.
