### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by hofst** [solrcloudpy/solrcloudpy#30]
Could you add Python 3 support? As far as I saw the code, 2to3 could to most of the work

**Comment by relwell** [comment]
Hey @hofst, sorry I missed this. I'd be okay with adding Python 3 support so long as it is backwards-compatible with 2.7. Please feel free to send me a pull request. I'd encourage you to run the tests through a few different versions of Solr (4.6, 5.3, and 6.0 would be good samples) before submitting.

**Comment by cheburakshu** [comment]
The package neither works with python3 nor python3. Below error in python3.

```

>>> import solrcloudpy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/solrcloudpy/__init__.py", line 1, in <module>
    from solrcloudpy.connection import SolrConnection
  File "/usr/local/lib/python3.4/dist-packages/solrcloudpy/connection.py", line 20, in <module>
    import solrcloudpy.collection as collection
  File "/usr/local/lib/python3.4/dist-packages/solrcloudpy/collection/__init__.py", line 37, in <module>
    from .admin import SolrCollectionAdmin
  File "/usr/local/lib/python3.4/dist-packages/solrcloudpy/collection/admin.py", line 4, in <module>
    from solrcloudpy.utils import SolrException, CollectionBase
  File "/usr/local/lib/python3.4/dist-packages/solrcloudpy/utils.py", line 5, in <module>
    import urlparse
ImportError: No module named 'urlparse'

```

**Comment by relwell** [comment]
That's right, it doesn't. Pull requests are welcome!
